spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        # === PRODUCTOR USUARIOS (POST al Event Grid) ===
        - id: productor-usuarios
          uri: https://productorusuarios.azurewebsites.net
          predicates:
            - Path=/api/usuarios
            - Method=POST
          filters:
            - RewritePath=/api/usuarios, /api/ProductorUsuarios

        # === CONSULTA USUARIOS (GraphQL) ===
        - id: consulta-usuarios
          uri: https://funcusuario.azurewebsites.net
          predicates:
            - Path=/api/graphql/usuarios
            - Method=POST
          filters:
            - RewritePath=/api/graphql/usuarios, /api/ConsultaUsuarios

        # === PRODUCTOR ROLES (POST al Event Grid) ===
        - id: productor-roles
          uri: https://productorusuarios.azurewebsites.net
          predicates:
            - Path=/api/roles
            - Method=POST
          filters:
            - RewritePath=/api/roles, /api/ProductorRoles

        # === CONSULTA ROLES (GraphQL) ===
        - id: consulta-roles
          uri: https://funcionroles.azurewebsites.net
          predicates:
            - Path=/api/graphql/roles
            - Method=POST
          filters:
            - RewritePath=/api/graphql/roles, /api/ConsultaRoles

  globalcors:
    corsConfigurations:
      '[/**]':
        allowedOrigins: "http://localhost:4200"
        allowedMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        allowedHeaders: "*"
        allowCredentials: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG