spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        # Rutas para el microservicio de pacientes
        - id: micro-pacientes
          uri: http://54.163.92.93:8080/
          predicates:
            - Path=/api/pacientes/**
        # Rutas para el microservicio de alertas
        - id: micro-alertas
          uri: http://54.163.92.93:8080/
          predicates:
            - Path=/api/alertas/**
        # Rutas para el microservicio de señales vitales
        - id: micro-senales-vitales
          uri: http://54.163.92.93:8080/
          predicates:
            - Path=/api/senales-vitales/**
    globalcors:
      corsConfigurations:
        '[/**]':
          allowedOrigins: "http://localhost:4200"  # Ajusta esto según el origen de tu frontend
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowedHeaders: "*"
          allowCredentials: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG