spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        # Ruta para obtener usuarios (GET)
        - id: usuarios-get
          uri: https://funcusuario.azurewebsites.net/api/Usuarios
          predicates:
            - Path=/api/usuarios/**
            - Method=GET

        # Ruta para crear usuario (POST)
        - id: usuarios-post
          uri: https://funcusuario.azurewebsites.net/api/Usuarios
          predicates:
            - Path=/api/usuarios
            - Method=POST

        # Ruta para actualizar usuario (PUT)
        - id: usuarios-put
          uri: https://funcusuario.azurewebsites.net/api/Usuarios
          predicates:
            - Path=/api/usuarios
            - Method=PUT

        # Ruta para eliminar usuario (DELETE)
        - id: usuarios-delete
          uri: https://funcusuario.azurewebsites.net/api/Usuarios
          predicates:
            - Path=/api/usuarios
            - Method=DELETE

        # Ruta para obtener roles (GET)
        - id: roles-get
          uri: https://funcionroles.azurewebsites.net/api/Roles
          predicates:
            - Path=/api/roles/**
            - Method=GET

        # Ruta para crear rol (POST)
        - id: roles-post
          uri: https://funcionroles.azurewebsites.net/api/Roles
          predicates:
            - Path=/api/roles
            - Method=POST

        # Ruta para actualizar rol (PUT)
        - id: roles-put
          uri: https://funcionroles.azurewebsites.net/api/Roles
          predicates:
            - Path=/api/roles
            - Method=PUT

        # Ruta para eliminar rol (DELETE)
        - id: roles-delete
          uri: https://funcionroles.azurewebsites.net/api/Roles
          predicates:
            - Path=/api/roles
            - Method=DELETE


  globalcors:
    corsConfigurations:
      '[/**]':
        allowedOrigins: "http://localhost:4200"
        allowedMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        allowedHeaders: "*"
        allowCredentials: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG